### ISSUE TITLE
proxy password don't work on personal proxy

### ISSUE THREAD

**Issue by jmgfr** [meyergre/Compagnont411.me#6]
proxy password don't work because source call prefs.getString("**proxy_password**", "") and android key is set to **proxy_pasword**. Please add a "s" in settings.xml and ask user to add password again in  user preference. After that, personal proxy with authentification work fine.
Thank

**Comment by meyergre** [comment]
Since it could be annoying having to re-enter the password, I'll call prefs.getString("proxy_pasword", "") instead...
Anyway, thanks a lot for your help ! update will roll out very soon
